discord_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[[actions]]
users = ["239194802002853898"]
reaction = "ğŸ" # Bread Emoji

[[actions]]
users = ["336320366668677120"]
reaction = "ğŸ”¥" # Fire Emoji
filter = '(?i)\bmicrophones?\b|\bmics?\b'

[[actions]]
reaction = "ğŸ" # Bread Emoji
filter = '(?i)\bbread\b'

[[actions]]
reaction = "ğŸ”¥" # Fire Emoji
filter = '(?i)\bfire\b'
