discord_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[[actions]]
users = ["239194802002853898"]
reactions = ["ğŸ"] # Bread Emoji

[[actions]]
users = ["336320366668677120"]
reactions = ["ğŸ”¥"] # Fire Emoji
filter = '(?i)\bmicrophones?\b|\bmics?\b'

[[actions]]
reactions = ["ğŸ"] # Bread Emoji
filter = '(?i)\bbread\b'

[[actions]]
reactions = ["ğŸ”¥"] # Fire Emoji
filter = '(?i)\bfire\b'
